import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import socketServices from "@/utilities/SocketServices";
import { ChatProvider } from "@/providers/ChatProvider";
import { UserProvider } from "@/providers/UserProvider";
import { TabProvider } from "@/providers/TabProvider";
import Header from "@/components/Header";
import { ProfileProvider } from "@/providers/ProfileProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  socketServices.initializeSocket();

  return (
    <html lang="en">
      <UserProvider>
        <TabProvider>
          <ProfileProvider>

            <ChatProvider>
              <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen`}
              >
                <Header />
                {children}


              </body>
            </ChatProvider>
          </ProfileProvider>
        </TabProvider>
      </UserProvider>
    </html>
  );
}
